# For local development only
version: '3.8'

services:
  inbound-server:
    image: assort-takehome
    ports:
      - '3000:3000'
    env_file:
      - .env.dev
    volumes:
      - ./:/app
    command: ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '3000', '--reload']
